Revert "Make archiving the .zip an optional step"
This reverts commit 87f987dd9ebc6bfafd9eeea45aa41e810dac99b0.

It _has_ to be a .zip:
> Error: X.app must be a zip archive (.zip), flat installer
> package (.pkg), or UDIF disk image (.dmg), use 'notarytool submit
> --force' to skip this validation and submit anyway.